- name: Install docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: Add docker dependencies apt repository
  apt_repository:
    filename: ubuntu-sdk-team
    repo: ppa:ubuntu-sdk-team/ppa

- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Get lsb info
  raw: lsb_release -cs
  register: ret_lsb
  changed_when: False

- name: Add docker apt repository
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ret_lsb.stdout }} stable"

- name: Install docker ce
  apt:
    name:
      - "docker-ce={{ docker_version }}~*"
      - containerd.io
    update_cache: yes

- name: Add user to docker group
  user:
    name="{{ ansible_user | default(lookup('env', 'USER'), True) }}"
    group=docker
    append=yes
