- name: Add nvidia docker gpg key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey

- name: Get linux distribution
  shell: ". /etc/os-release && echo $ID$VERSION_ID"
  register: ret_dist
  changed_when: False

- name: Add nvidia docker apt repository
  get_url:
    url="https://nvidia.github.io/nvidia-docker/{{ ret_dist.stdout }}/nvidia-docker.list"
    dest=/etc/apt/sources.list.d/nvidia-docker.list

- name: Install nvidia docker2
  apt:
    name:
      - "nvidia-docker2={{ nvidia_docker2_version }}-*"
      - "nvidia-container-runtime={{ nvidia_container_runtime_version }}-*"
    update_cache: yes

- name: SIGHUP dockerd
  raw: pkill -SIGHUP dockerd
