- name: Install docker dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  become: yes

- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Get linux distribution
  raw: lsb_release -cs
  register: ret_dist

- name: Add docker apt repository
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ret_dist.stdout }} stable"
  become: yes

- name: Install docker ce
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - "docker-ce={{ docker_version }}.*"
    - "docker-ce-cli={{ docker_version }}.*"
    - containerd.io
  become: yes

- name: Add user to docker group
  user:
    name="{{ ansible_user | default(lookup('env', 'USER'), True) }}"
    group=docker
    append=yes
  become: yes
