- name: Check docker
  stat: /var/run/docker.sock
  register: stat_docker

- name: Install docker
  include_tasks: docker.ubuntu.yml
  when:
    - stat_docker.stat.exists
    - ansible_distribution == 'Ubuntu'

- name: Install docker
  include_tasks: docker.centos.yml
  when:
    - stat_docker.stat.exists
    - ansible_distribution == 'CentOS'

- name: Install nvidia-docker
  include_tasks: nvidia_docker_plugin.ubuntu.yml
  when:
    - enable_nvidia_gpu
    - ansible_distribution == 'Ubuntu'

- name: Install nvidia-docker
  include_tasks: nvidia_docker_plugin.centos.yml
  when:
    - enable_nvidia_gpu
    - ansible_distribution == 'CentOS'
